# Generated by Django 5.0 on 2025-01-07 16:40

import django.core.validators
import forum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_userprofile_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500, validators=[django.core.validators.MinLengthValidator(10, message='La bio doit contenir au moins 10 caractères'), django.core.validators.MaxLengthValidator(500, message='La bio ne peut pas dépasser 500 caractères'), forum.models.validate_bio_content], verbose_name='Biographie'),
        ),
    ]
