# Generated by Django 5.1.3 on 2025-01-14 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_captcharequirement_loginattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='content',
        ),
        migrations.AddField(
            model_name='activity',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.comment'),
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('new_topic', 'Nouvelle discussion'), ('new_reply', 'Nouvelle réponse'), ('new_member', 'Nouveau membre')], default='new_member', max_length=20),
        ),
    ]
